# Generated by Django 2.2.6 on 2019-10-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transimage',
            old_name='base',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='transimage',
            name='style',
        ),
    ]
