# Generated by Django 2.2.6 on 2019-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191206_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
