# Generated by Django 2.2.6 on 2019-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191102_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='base'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='style',
            field=models.ImageField(upload_to='style'),
        ),
    ]
