# Generated by Django 2.2.6 on 2019-11-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191102_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='baseimagepath',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='outputimage',
            field=models.ImageField(default=1, upload_to='projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='styleimagepath',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
