# Generated by Django 2.2.6 on 2019-11-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191103_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='outputimage',
        ),
        migrations.AddField(
            model_name='photo',
            name='outputimagepath',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
