# Generated by Django 2.2.6 on 2019-11-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage'),
        ),
    ]
