# Generated by Django 2.2.6 on 2019-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191112_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default=1, upload_to='profileimage'),
            preserve_default=False,
        ),
    ]
